{% set version = "0.13.0" %}

# handle magic python variables
{% set python_min = python_min | default("3.9") %}
{% set PYTHON = PYTHON | default("$PYTHON") %}


package:
  name: typer-split
  version: {{ version }}

source:
  - folder: typer-slim
    url: https://pypi.org/packages/source/t/typer-slim/typer_slim-{{ version }}.tar.gz
    sha256: 7d7d3b0ad211ddcc9bcfe3d51e7d5903b0f10ae07938cca33f8af1f578c5007b
  - folder: typer-cli
    url: https://pypi.org/packages/source/t/typer-cli/typer_cli-{{ version }}.tar.gz
    sha256: 9935e5ffdbbd7c435f5d61dcb0e303fe8c81ef0c69968999a26d333456af3ba6
    patches:
      - 0000-typer-cli-no-entry-point.patch
  - folder: typer
    url: https://pypi.org/packages/source/t/typer/typer-{{ version }}.tar.gz
    sha256: f1c7198347939361eec90139ffa0fd8b3df3a2259d5852a0f7400e476d95985c

build:
  number: 0
  noarch: python

outputs:
  # packages with source are `noarch: python`, and should use `{{ min_python }}` in `host` and `run``
  - name: typer-slim
    build:
      noarch: python
      script: {{ PYTHON }} {{ RECIPE_DIR }}/build_typer.py
    requirements:
      host:
        - python {{ python_min }}.*
        - pdm-backend
        - pip
        - python-build
      run:
        - python >={{ python_min }}
        - click >=8.0.0
        - typing_extensions >=3.7.4.3
      run_constrained:
        # avoid clobbering historic `typer` versions
        - {{ pin_subpackage("typer", max_pin="x.x.x") }}
        # see typer-slim-standard `run` for concrete pinss
        - rich >=10.11.0
        - shellingham >=1.3.0
    test:
      requires:
        - pip
        - python {{ python_min }}.*
      commands:
        - pip check

  - name: typer-cli
    build:
      noarch: python
      script: {{ PYTHON }} {{ RECIPE_DIR }}/build_typer.py
    requirements:
      host:
        - python {{ python_min }}.*
        - pdm-backend
        - pip
        - python-build
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("typer", exact=True) }}
    test:
      requires:
        - pip
        - python {{ python_min }}.*
      commands:
        - pip check
        - typer --version
        - typer --help

  - name: typer
    build:
      noarch: python
      script: {{ PYTHON }} {{ RECIPE_DIR }}/build_typer.py
      entry_points:
        # won't actually run, but needs to be here to get proper wrapper generated
        - typer = typer.cli:main
    requirements:
      host:
        - python {{ python_min }}.*
        - pdm-backend
        - pip
        - python-build
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("typer-slim-standard", exact=True) }}
    test:
      source_files:
        - typer/tests
        - typer/docs_src
      requires:
        - pip
        - pytest
        - coverage
      commands:
        - pip check
        - typer --version
        - typer --help
        - cd typer && coverage run --source=typer --branch -m pytest -vv --color=yes --tb=long -k "not ((multiple_values and main) or completion)"
        - coverage report --show-missing --skip-covered --fail-under=66

  # dep-only packages are `noarch: generic`, with no `host`
  - name: typer-slim-standard
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("typer-slim", exact=True) }}
        # see `typer-slim` for pins in `run_constrained`
        - rich
        - shellingham
    test:
      source_files:
        - typer-slim/tests
        - typer-slim/docs_src
      imports:
        - typer
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/tiangolo/typer
  license: MIT
  license_family: MIT
  license_file: typer-slim/LICENSE
  summary: Typer, build great CLIs. Easy to code. Based on Python type hints.
  doc_url: https://typer.tiangolo.com

extra:
  feedstock-name: typer
  recipe-maintainers:
    - dfornika
    - bollwyvl
    - fcollonval
